site_name: 史上最弱ACM模板
site_url: http://xuanwo.org/
repo_url: https://github.com/Xuanwo/ACMTemplate
site_description: 正如你所见，这是史上最弱的模板= =
site_author: Xuanwo
site_favicon: favicon.ico
pages:
- ['index.md', '简介']
- ['number-theory.md', '数论','质因数']

copyright: Copyright &copy; 2015, <a href="http://xuanwo.org/">Xuanwo</a>.